volumes:
  thesillyhome_config:
    name: thesillyhome_config
  ignore:
    name: ignore

services:
  thesillyhome:
    container_name: thesillyhome
    image: Lightningpicture/thesillyhome-container:beta_v1.2.2

    restart: unless-stopped
    volumes:
      - .\thesillyhome_src\appdaemon\apps\:/thesillyhome_src/appdaemon/apps/
      - .\thesillyhome_src\startup\:/thesillyhome_src/startup/
      - .\thesillyhome_src\thesillyhome\:/thesillyhome_src/thesillyhome/
      - .\thesillyhome_src\frontend\src\:/thesillyhome_src/frontend/src/
      - thesillyhome_config:/thesillyhome_src/data/config/
    ports:
      - "2300:2300"
      - "3000:3000"
