volumes:
  thesillyhome_config:
    name: thesillyhome_config
    external: true

services:
  thesillyhome:
    container_name: thesillyhome
    image: lightningpicture/aarch64-thesillyhome-dev:dev-33
    restart: unless-stopped
    volumes:
      - thesillyhome_config:/thesillyhome_src/data/config/
    ports:
      - 2300:2300
